name: bia-eb
services:
  server:
 env_file: .env
    container_name: bia
    image: 557772028142.dkr.ecr.us-east-1.amazonaws.com/bia:568ba24_2024-04-18
    ports:
    - mode: ingress
      target: 8080
      published: "80"
      protocol: tcp
